# Generated by Django 4.1.5 on 2023-01-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('edu', 'education'), ('job', 'job'), ('per', 'personal'), ('fam', 'family')], default='per', max_length=3),
        ),
    ]
